spark:
  app_name: "TrustGauge"
  master: "local[*]"
  driver_memory: "4g"
  executor_memory: "4g"
  config:
    spark.sql.execution.arrow.pyspark.enabled: true
    spark.driver.maxResultSize: "2g"
    spark.sql.shuffle.partitions: 100

data:
  input_path: "data/raw/"
  processed_path: "data/processed/"
  sample_fraction: 0.1
  random_seed: 42

nlp:
  model_name: "distilbert-base-uncased-finetuned-sst-2-english"
  max_length: 512
  batch_size: 32

trust_score:
  weights:
    verified_purchase: 0.3
    helpful_votes: 0.2
    review_length: 0.15
    sentiment_score: 0.2
    fake_probability: -0.15

fake_detection:
  contamination: 0.1
  random_seed: 42

visualization:
  theme: "default"
  port: 7860

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/trustgauge.log"

api:
  host: "0.0.0.0"
  port: 8000
  debug: false 